Repository Prem-Kumar-Dev/hacktoberfest2024-project, pull requests merged in 2024-10, with the labels that each got.

#6 Added Merge Sort program in C and Python
  C/Merge_Sort.c
  Python/Merge_Sort.py
Labels: enhancement, open-source

#7 Add Floyd-Warshall implementation in C
  C/Floyd-Warshall.c
Labels: enhancement, open-source

#8 Add Travelling Saleman Problem implementation in C
  C/TravellingSalemanProblem.c
Labels: enhancement, hacktoberfest-accepted, open-source

#10 Prem kumar dev3
  CPP/test.cpp
  Scripts/CLI/PDF Merger/README.md
  Scripts/CLI/PDF Merger/pdf_merger.py
  Scripts/CLI/PDF Merger/pdf_merger/__init__.py
  Scripts/CLI/PDF Merger/pdf_merger/__pycache__/__init__.cpython-312.pyc
  Scripts/CLI/PDF Merger/pdf_merger/__pycache__/cli.cpython-312.pyc
  Scripts/CLI/PDF Merger/pdf_merger/__pycache__/merger.cpython-312.pyc
  Scripts/CLI/PDF Merger/pdf_merger/cli.py
  Scripts/CLI/PDF Merger/pdf_merger/merger.py
  Scripts/CLI/PDF Merger/requirements.txt
Labels: enhancement, hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#11 Create UniqueNumbers.java
  Java/UniqueNumbers.java
Labels: enhancement, hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#13 Implement Prim's and Kruskal's Algorithms in CPP
  CPP/KruskalAlgorithm.cpp
  CPP/PrimsAlgorithm.cpp
Labels: enhancement, hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#14 Implementing Topological sort in C++
  CPP/TOPOSORT.cpp
Labels: enhancement, hacktoberfest, hacktoberfest2024, hacktoberfest-accepted

#18 Create FibonacciSeries.cpp
  CPP/FibonacciSeries.cpp
Labels: enhancement, hacktoberfest, hacktoberfest2024, hacktoberfest-accepted
